export type Authority = 'L0' | 'L1' | 'L2' | 'L3'
export type Risk = 'LOW' | 'MEDIUM' | 'HIGH'
export type UserRole = 'EMPLOYEE' | 'OWNER' | 'ADMIN'
export type AssetType = 'DOCUMENT' | 'AUDIO' | 'VIDEO' | 'IMAGE'
export type BusinessType =
  | 'PRODUCT_DOCUMENT'
  | 'SOLUTION'
  | 'POLICY'
  | 'PROCESS'
  | 'TRAINING'
  | 'CUSTOMER_MEETING'
  | 'INTERNAL_MEETING'
  | 'PROJECT_DOCUMENT'
  | 'SESSION_UPLOAD'
  | 'OTHER'
export type ProcessStatus = 'NEW' | 'PROCESSING' | 'PROCESSED' | 'FAILED'
export type KnowledgeType =
  | 'PRODUCT_CAPABILITY'
  | 'PRODUCT_PARAMETER'
  | 'TECHNICAL'
  | 'FAQ'
  | 'PROCESS'
  | 'POLICY'
  | 'BEST_PRACTICE'
  | 'PROJECT'
  | 'OTHER'
export type Relation = 'NEW' | 'DUPLICATE' | 'UPDATE' | 'CONFLICT'
export type CandidateStatus = 'PENDING' | 'NEEDS_CHANGES' | 'APPROVED' | 'REJECTED'
export type TriggerType = 'CANDIDATE' | 'USER_FEEDBACK' | 'LIFECYCLE' | 'SOURCE_CHANGE'
export type ReviewType = 'NEW' | 'UPDATE' | 'CONFLICT' | 'STALE'
export type ReviewStatus = 'PENDING' | 'CHANGES_REQUESTED' | 'RESOLVED' | 'CANCELLED'
export type ResolutionAction =
  | 'CREATE_KNOWLEDGE'
  | 'UPDATE_KNOWLEDGE'
  | 'KEEP_CURRENT'
  | 'REJECT_CANDIDATE'
  | 'ARCHIVE_KNOWLEDGE'
  | 'CONFIRM_VALID'
  | 'MARK_DUPLICATE'
  | 'SPLIT_BY_SCOPE'
  | 'MARK_INSUFFICIENT'
export type ReviewDecision = 'PUBLISH' | 'REQUEST_CHANGES' | 'REJECT' | 'TRANSFER'
export type ProblemTag =
  | 'DUPLICATE'
  | 'OVERLAP'
  | 'CONFLICT'
  | 'INSUFFICIENT_EVIDENCE'
  | 'MISSING_SCOPE'
  | 'OUTDATED'
  | 'OCR_ERROR'
  | 'SOURCE_UNCLEAR'
export type CrossDocumentRelationType =
  | 'EXACT_DUPLICATE'
  | 'OVERLAP'
  | 'COMPLEMENTARY'
  | 'CONDITIONAL_VARIANT'
  | 'CONFLICT'
  | 'INSUFFICIENT'
export type CrossDocumentRelationStatus = 'AUTO_RESOLVED' | 'PENDING' | 'RESOLVED'
export type KnowledgeSourceRole = 'PRIMARY' | 'SUPPORTING' | 'ALIAS'
export type FeedbackType = 'WRONG' | 'OUTDATED' | 'MISSING' | 'CITATION_ERROR' | 'OTHER'
export type KnowledgeStatus = 'ACTIVE' | 'STALE' | 'ARCHIVED'
export type IndexStatus = 'PENDING' | 'INDEXED' | 'FAILED'
export type ConversationScope = 'ENTERPRISE' | 'SESSION' | 'BOTH'
export type ConversationStatus = 'ACTIVE' | 'ARCHIVED'
export type MessageRole = 'USER' | 'ASSISTANT'
